// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract StudentData {
    // Structure to represent a student
    struct Student {
        uint256 studentId;
        string name;
        uint256 age;
    }

    // Array to store student records, marked as private to avoid autogenerated getter
    Student[] private students;

    // Fallback function to receive ether
    receive() external payable {
        // This fallback function can be used to receive funds
    }

    // Add a new student record
    function addStudent(uint256 _studentId, string memory _name, uint256 _age) public {
        Student memory newStudent = Student(_studentId, _name, _age);
        students.push(newStudent);
    }

    // Get the number of students
    function getNumberOfStudents() public view returns (uint256) {
        return students.length;
    }

    // Get student details by studentId
    function getStudentById(uint256 _studentId) public view returns (uint256, string memory, uint256) {
        for (uint256 i = 0; i < students.length; i++) {
            if (students[i].studentId == _studentId) {
                Student memory student = students[i];
                return (student.studentId, student.name, student.age);
            }
        }
        revert("Student not found");
    }

    // Update student details by studentId
    function updateStudent(uint256 _studentId, string memory _newName, uint256 _newAge) public {
        for (uint256 i = 0; i < students.length; i++) {
            if (students[i].studentId == _studentId) {
                Student storage student = students[i];
                student.name = _newName;
                student.age = _newAge;
                return;
            }
        }
        revert("Student not found");
    }
}
